services:
  website:
    container_name: website
    image: nginx:latest
    volumes:
      - .:/usr/share/nginx/html
    environment:
      VIRTUAL_HOST: bnbnb.link
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: bnbnb.link
      LETSENCRYPT_EMAIL: pulpfictiontaxidriver@yahoo.co.jp
    networks:
      - shared

networks:
  shared:
    external: true
 